api_login_check:
    path: /api/login_check
api_refresh_token:
    path: /api/token/refresh

user_controllers:
    resource:
        path: ../src/User/Application/Controller/Api
        namespace: App\User\Application\Controller\Api
    type: attribute
